upstream backend_a {
    least_conn;
    server server-c:9006;
    server server-a:9006;
    server server-b:9006;
}

server {
    listen 9006;


    location / {
        proxy_pass http://backend_a;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection keep-alive;
    }
}
